module performance_test {
  module msg {
    // 8 bytes for time
    // 8 bytes for id
    // 32 - 16 = 16
    typedef octet octet__32[16];
    struct Array32 {
      octet__32 array;

      long long time;

      unsigned long long id;
    };
  }; // msg
}; // performance_test
