module performance_test {
  module msg {
    // 8 bytes for time
    // 8 bytes for id
    // 64 - 16 = 48
    typedef octet octet__64[48];
    struct Array64 {
      octet__64 array;

      long long time;

      unsigned long long id;
    };
  }; // msg
}; // performance_test
