module performance_test {
  module msg {
    // 8 bytes for time
    // 8 bytes for id
    // 4194304 - 16 = 4194288
    typedef octet octet__4194304[4194288];
    struct Array4m {
      octet__4194304 array;

      long long time;

      unsigned long long id;
    };
  }; // msg
}; // performance_test
