module performance_test {
  module msg {
    // 8 bytes for time
    // 8 bytes for id
    // 2097152 - 16 = 2097136
    typedef octet octet__2097152[2097136];
    struct Array2m {
      octet__2097152 array;

      long long time;

      unsigned long long id;
    };
  }; // msg
}; // performance_test
