module performance_test {
  module msg {
    // 8 bytes for time
    // 8 bytes for id
    // 1024 - 16 = 1008
    typedef octet octet__1024[1008];
    struct Array1k {
      octet__1024 array;

      long long time;

      unsigned long long id;
    };
  }; // msg
}; // performance_test
