module performance_test {
  module msg {
    // 8 bytes for time
    // 8 bytes for id
    // 16384 - 16 = 16368
    typedef octet octet__16384[16368];
    struct Array16k {
      octet__16384 array;

      long long time;

      unsigned long long id;
    };
  }; // msg
}; // performance_test
