module performance_test {
  module msg {
    // 8 bytes for time
    // 8 bytes for id
    // 61440 - 16 = 61424
    typedef octet octet__61440[61424];
    struct Array60k {
      octet__61440 array;

      long long time;

      unsigned long long id;
    };
  }; // msg
}; // performance_test
