module performance_test {
  module msg {
    typedef sequence<octet, 8388608> bounded__octet__8388608;
    struct BoundedSequence8m {
      bounded__octet__8388608 bounded_sequence;

      long long time;

      unsigned long long id;
    };
  }; // msg
}; // performance_test
