module performance_test {
  module msg {
    typedef sequence<octet, 4096> bounded__octet__4096;
    struct BoundedSequence4k {
      bounded__octet__4096 bounded_sequence;

      long long time;

      unsigned long long id;
    };
  }; // msg
}; // performance_test
